### ISSUE TITLE
InputJobInfo异常

### ISSUE THREAD

**Issue by gjhkael** [dianping/hive#54]
@ErikFang 你好，我在实际工作中遇到了一个问题，InputJobInfo.java的序列化和反序列化代码注释了，这会导致HcatMutilnputFormat进行序列化和反序列化的过程中导致获取不到InputSplit信息。而使用这两个函数的话会出现：
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
    at java.io.ObjectInputStream.readTypeString(ObjectInputStream.java:1418)
    at java.io.ObjectStreamClass.readNonProxy(ObjectStreamClass.java:705)
    at java.io.ObjectInputStream.readClassDescriptor(ObjectInputStream.java:830)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1601)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
    at java.util.ArrayList.readObject(ArrayList.java:771)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
    at org.apache.hive.hcatalog.common.HCatUtil.deserialize(HCatUtil.java:117)
    at org.apache.hive.hcatalog.mapreduce.HCatMultiInputFormat.getJobInfoList(HCatMultiInputFormat.java:79)
的异常。
请问您这边有没有好的解决方法？

**Comment by gjhkael** [comment]
问题已经解决，具体还是参考了hive1.2.1的代码。
